platform: graphics: add arcvm support to record_cros_trace
This requires communication with ARCVM perfetto over host adb
and gathering guest time sync data with an interim app that
reads CPU counters and adds them to perfetto periodically.

APK is landed in the vperfetto project:
https://github.com/741g/vperfetto/commit/0940f171345b9a3ccb8deec52c4ac8d368eb8cda

BUG=b:197165177
TEST=record_merge_trace DUT DUT-arcvm virgls wm gfx

Change-Id: I32e31a84e3a3581419e31bd77b8e551e1b0f496b
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/graphics/+/3105718
Tested-by: John Bates <jbates@chromium.org>
Reviewed-by: Yiwei Zhang <zzyiwei@chromium.org>
Commit-Queue: John Bates <jbates@chromium.org>

diff --git a/src/perfetto/record_cros_trace b/src/perfetto/record_cros_trace
--- a/src/perfetto/record_cros_trace
+++ b/src/perfetto/record_cros_trace
@@ -5,16 +5,17 @@
 
 if [[ "$1" = "--help" ]]; then
   echo "syntax: $0"
-  echo "  [--ssh device]           IP of device or VM to trace (default" \
+  echo "  [--ssh <device>]         IP of device or VM to trace (default" \
        "is local trace)"
-  echo "  [-t duration_ms]         Duration to trace (default is until Ctrl+C)"
-  echo "  [-o output_file]"
-  echo "  [-b buffer_size_kb]      Size of trace buffer in KB"
+  echo "                           Append -arcvm to <device> to trace ARCVM"
+  echo "  [-t <duration_ms>]       Duration to trace (default is until Ctrl+C)"
+  echo "  [-o <output_file>]"
+  echo "  [-b <buffer_size_kb>]    Size of trace buffer in KB"
   echo "  [-p /path/to/perfetto]   Path to perfetto tool if it's not in \$PATH"
-  echo "  [-i period_ms]           Incremental update period in ms"
+  echo "  [-i <period_ms>]         Incremental update period in ms"
   echo "  [--no-ftrace]            Do not include ftrace sched data"
-  echo "  [-d category] ...           Disabled categories"
-  echo "  [category] [category] ...   Enabled categories"
+  echo "  [-d <category>] ...             Disabled categories"
+  echo "  [<category>] [<category>] ...   Enabled categories"
   echo "examples:"
   echo "  $0 --ssh DUT                      trace on DUT until Ctrl C"
   echo "  $0 --ssh DUT -t 1000              trace for 1 second"
@@ -25,13 +26,15 @@ if [[ "$1" = "--help" ]]; then
 fi
 
 dut=''
+is_arcvm=false
 time_ms=''
 ftrace=true
 categories=()
 disabled_categories=()
 now=$(date +"%Y-%m-%d_%H-%M-%S")
 output_file=''
-config_file="/tmp/perfetto-${RANDOM}.config"
+config_filename="perfetto-${RANDOM}.config"
+config_filepath="/tmp/${config_filename}"
 perfetto=perfetto
 incremental_update_period_ms=1000
 buffer_size_kb=100000
@@ -80,9 +83,24 @@ if [[ -z "${output_file}" ]]; then
   fi
 fi
 
+target_name="local"
+[[ -z "${dut}" ]] || target_name="${dut}"
+
+atrace_categories=()
+if [[ "${dut}" == *-arcvm ]]; then
+  is_arcvm=true
+  dut="${dut%"-arcvm"}"
+  # Filter categories for atrace catgories.
+  atrace_allowed=$(ssh -q "${dut}" "adb shell atrace --list" \
+      | sed -r 's/ *(.*) - .*/\1/g')
+  atrace_categories=($(comm -12 \
+      <(echo "${atrace_allowed}" | tr ' ' '\n' | sort ) \
+      <(echo "${categories[@]}" | tr ' ' '\n' | sort)))
+fi
+
 # Write perfetto config file
 
-cat >"${config_file}" <<EOL
+cat >"${config_filepath}" <<EOL
 buffers: {
   size_kb: ${buffer_size_kb}
   fill_policy: ${fill_policy}
@@ -105,8 +123,8 @@ data_sources: {
 }
 EOL
 
-if [[ "${ftrace}" = true ]]; then
-  cat >>"${config_file}" <<EOL
+if [[ "${ftrace}" == true ]]; then
+  cat >>"${config_filepath}" <<EOL
 data_sources: {
     config {
         name: "linux.ftrace"
@@ -115,6 +133,7 @@ data_sources: {
             # frequently it gets moved into the userspace buffer defined above.
             buffer_size_kb: 16384
             drain_period_ms: 250
+            ftrace_events: "ftrace/print"
             ftrace_events: "power/cpu_frequency"
             ftrace_events: "power/cpu_idle"
             ftrace_events: "power/suspend_resume"
@@ -133,13 +152,22 @@ data_sources: {
             ftrace_events: "tracing_mark_write"
             ftrace_events: "thermal/thermal_temperature"
             ftrace_events: "thermal/cdev_update"
+EOL
+
+for (( i = 0; i < ${#atrace_categories[@]}; i++ ));
+do
+  echo "            atrace_categories: \"${atrace_categories[${i}]}\"" >> \
+      "${config_filepath}"
+done
+
+cat >>"${config_filepath}" <<EOL
         }
     }
 }
 EOL
 fi
 
-cat >>"${config_file}" <<EOL
+cat >>"${config_filepath}" <<EOL
 data_sources: {
     config {
         name: "linux.sys_stats"
@@ -170,38 +198,106 @@ EOL
 for (( i = 0; i < ${#categories[@]}; i++ ));
 do
   echo "            enabled_categories: \"${categories[${i}]}\"" >> \
-       "${config_file}"
+       "${config_filepath}"
 done
 
 for (( i = 0; i < ${#disabled_categories[@]}; i++ ));
 do
   echo "            disabled_categories: \"${disabled_categories[${i}]}\"" >> \
-       "${config_file}"
+       "${config_filepath}"
 done
 
-cat >>"${config_file}" <<EOL
+cat >>"${config_filepath}" <<EOL
         }
     }
 }
 EOL
 
-if [[ -n "${time_ms}" ]]; then
-  echo "duration_ms: ${time_ms}" >> "${config_file}"
-else
-  echo "Press Ctrl+C to stop tracing..."
+if [[ "${is_arcvm}" == true ]]; then
+  cat >>"${config_filepath}" <<EOL
+data_sources: {
+    config {
+        name: "android.log"
+        android_log_config {
+            min_prio: PRIO_VERBOSE
+            log_ids: LID_DEFAULT
+            log_ids: LID_SYSTEM
+            log_ids: LID_EVENTS
+            log_ids: LID_CRASH
+        }
+    }
+}
+data_sources: {
+    config {
+        name: "android.surfaceflinger.frametimeline"
+    }
+}
+EOL
 fi
+
+dut_trace="/tmp/perfetto-trace-${RANDOM}"
+arcvm_trace="/data/misc/perfetto-traces/trace"
+
+# Kick off background perfetto trace.
 
 if [[ -z "${dut}" ]]; then
-  # Kick off the perfetto command locally
-  "${perfetto}" -c "${config_file}" --txt -o "${output_file}" || exit 1
+  "${perfetto}" -c "${config_filepath}" --txt --background \
+      -o "${output_file}" > /dev/null || exit 1
 else
-  # Kick off the perfetto command on the DUT
-  scp -q "${config_file}" "${dut}:${config_file}" || exit 1
-  ssh "${dut}" '[[ -n $(pgrep traced) ]] || start traced' 2> /dev/null
-  ssh -q -t "${dut}" "${perfetto}" -c "${config_file}" --txt -o \
-      /tmp/perfetto-trace || exit 1
-  scp -q "${dut}:/tmp/perfetto-trace" "${output_file}" && \
-      ssh "${dut}" rm /tmp/perfetto-trace || exit 1
+  if [[ "${is_arcvm}" == true ]]; then
+    cat "${config_filepath}" | ssh "${dut}" \
+        "adb shell perfetto -c - --txt --background --o ${arcvm_trace}" \
+        > /dev/null || exit 1
+  else
+    # Try to start traced if it's not already running.
+    ssh "${dut}" '[[ -n $(pgrep traced) ]] || start traced' 2> /dev/null
+    cat "${config_filepath}" | ssh "${dut}" "${perfetto}" -c - --txt \
+        --background -o "${dut_trace}" > /dev/null || exit 1
+  fi
 fi
 
-echo "${output_file}"
+# Wait for timeout or interrupt.
+
+time_string=''
+[[ -n "${time_ms}" ]] && time_string=" for ${time_ms} ms"
+[[ -z "${time_ms}" ]] && time_ms=$((24*60*60*1000)) # 24 hours by default.
+cur_time_ns=$(date +%s%N)
+wait_ns="${time_ms}000000"
+end_time_ns=$((cur_time_ns + wait_ns))
+stop_waiting () { end_time_ns="${cur_time_ns}" ; }
+trap "echo ; stop_waiting" SIGINT
+trap "stop_waiting" SIGUSR1
+
+echo "Tracing ${target_name}${time_string}... press Ctrl-C to stop"
+# Note this sleep is intentionally short because parent script may
+# send us a SIGUSR1 that we only handle in between sleeps.
+while [[ ( $(date +%s%N) < "${end_time_ns}" ) ]]; do sleep 0.1; done
+
+trap - SIGINT SIGUSR1
+
+# Kill all perfetto processes and wait for them to finish.
+
+echo "Please wait: copying trace from ${target_name}..."
+
+wait_finish () {
+  while [[ -n $($1) ]]; do sleep 0.2; done
+}
+
+if [[ -z "${dut}" ]]; then
+  killall perfetto
+  wait_finish "pgrep perfetto"
+else
+  if [[ "${is_arcvm}" == true ]]; then
+    ssh -q "${dut}" "adb shell killall perfetto"
+    wait_finish "ssh -q ${dut} adb shell pgrep perfetto"
+    ssh -q "${dut}" "adb pull ${arcvm_trace} ${dut_trace}" > /dev/null \
+        || { echo "error: failed to adb pull" ; exit 1; }
+  else
+    ssh -q "${dut}" 'kill $(pgrep perfetto)'
+    wait_finish "ssh -q ${dut} pgrep perfetto"
+  fi
+  scp -q "${dut}:${dut_trace}" "${output_file}" && \
+      ssh "${dut}" rm "${dut_trace}" || exit 1
+fi
+
+ls -hs "${output_file}"
diff --git a/src/perfetto/record_merge_trace b/src/perfetto/record_merge_trace
--- a/src/perfetto/record_merge_trace
+++ b/src/perfetto/record_merge_trace
@@ -17,7 +17,9 @@ HOST AND GUEST SETUP
  - perCetto library installed (https://github.com/olvaffe/percetto)
  - perfetto installed (perfetto tool must be in PATH).
  - code instrumented with frequent* perCetto trace events.
- - traced service running
+ - traced service running.
+ - [for ARCVM] developer mode and adb enabled.
+ - only up to 2 VMs can run simultaneously, one of them being ARCVM.
 * There must be frequent events on both host and guest for merging to
   work. The incremental update in perCetto will contain this time sync data.
   That defaults to 1 second intervals. Pass -i <ms> to change that period for
@@ -30,10 +32,13 @@ HOST AND GUEST SETUP
 
 if [[ "$1" = "--help" ]] || [[ -z "$1" ]] || [[ -z "$2" ]]; then
   echo "syntax: $0 <host-ssh-ip> <guest-ssh-ip> [args for record_cros_trace]..."
-  echo "example: $0 hostip guestip -t 5000 mesa gl virgl virgls"
+  echo "example: $0 hostip guestip -t 5000 virgl virgls"
+  echo "example: $0 hostip hostip-arcvm virgl virgls gfx wm view"
+  echo "         Without the -t option, you will need to Ctrl+C on both sides"
   exit 1
 fi
 
+verbose=false
 vperfetto_merge=vperfetto_merge
 record_cros_trace=record_cros_trace
 command -v "${vperfetto_merge}" > /dev/null 2>&1 || \
@@ -47,33 +52,99 @@ rm -f "${host_file}" "${guest_file}"
 
 host=$1
 guest=$2
-inc_update_ms=1000
-cmd1="${record_cros_trace} --ssh ${host} -i ${inc_update_ms} \
-  -o ${host_file} ${@:3}"
-cmd2="${record_cros_trace} --ssh ${guest} -i ${inc_update_ms} \
-  -o ${guest_file} ${@:3}"
 
-tmux new-session -d bash
-tmux split-window -h bash
-tmux send -t 0:0.0 "${cmd1}; sleep 3; exit" C-m
-tmux send -t 0:0.1 "${cmd2}; sleep 3; exit" C-m
-tmux -2 attach-session -d
-
-# capture tsc-offset from the host to synchronize host and guest timestamps
-path_tsc_offset=$(ssh "${host}" find /sys/kernel/debug/ -name "tsc-offset" \
-                  -print -quit)
-if [[ -z "${path_tsc_offset}" ]]; then
-  echo "error: guest tsc offset not found -- is guest running?"
-  exit 1
+# Determine what tsc-offset to use. Debugfs has files for each VM.
+# This script supports at most two VMs running: ARCVM + one other.
+is_arcvm=false
+if [[ "${guest}" == *-arcvm ]]; then
+  is_arcvm=true
 fi
-tsc_offset=$(ssh "${host}" cat "${path_tsc_offset}")
-echo "guest tsc-offset is ${tsc_offset}"
+
+sync_app="com.google.perfettoguesttimesync"
+
+if [[ "${is_arcvm}" == true ]]; then
+  found=$(ssh -q "${host}" "adb shell pm list packages | grep ${sync_app}")
+  if [[ -z "${found}" ]]; then
+    echo "attempting to install ${sync_app} from vperfetto..."
+    apk=$(dirname $(which "${vperfetto_merge}"))
+    apk="${apk}/../utils/arcvm-time-sync-app/app/release/app-release.apk"
+    scp "${apk}" "${host}":/tmp/app.apk \
+        || print_prereqs_and_exit "error: could not find ${apk}"
+    ssh -q "${host}" "adb install -r /tmp/app.apk" || exit 1
+  fi
+  ssh -q "${host}" "adb shell am start ${sync_app}/${sync_app}.MainActivity" \
+      > /dev/null
+fi
+
+find_tsc_offsets="find /sys/kernel/debug/ -name 'tsc-offset'"
+
+vm_pids=$(ssh -q "${host}" "${find_tsc_offsets}" \
+          | sed -r 's/.*kvm\/([0-9]*).*/\1/g' | sort | uniq)
+
+if [[ $(echo "{vm_pids}" | wc -w) -gt "2" ]]; then
+  print_prereqs_and_exit "error: more than 2 VMs are running"
+fi
+
+found_guest_pid=''
+for pid in ${vm_pids}
+do
+  cmd_arcvm=$(ssh -q "${host}" "cat /proc/${pid}/cmdline" \
+              | grep arcvm > /dev/null && echo arcvm)
+  if [[ "${is_arcvm}" == true ]]; then
+    if [[ "${cmd_arcvm}" == "arcvm" ]]; then
+      found_guest_pid="${pid}"
+    fi
+  else
+    if [[ ! "${cmd_arcvm}" == "arcvm" ]]; then
+      found_guest_pid="${pid}"
+    fi
+  fi
+done
+
+if [[ -z "${found_guest_pid}" ]] && [[ "${is_arcvm}" == true ]]; then
+  # ARC++ is detected.
+  tsc_offset=0
+  echo "warning: ARC++ perfetto may not support --txt config option"
+else
+  if [[ -z "${found_guest_pid}" ]]; then
+    echo "error: guest tsc offset not found -- is guest running?"
+    exit 1
+  fi
+
+  # Make sure the tsc offsets are all the same for each vcpu.
+  tsc_offset=$(ssh -q "${host}" "${find_tsc_offsets} \
+              | grep ${found_guest_pid}- | xargs cat" | uniq)
+
+  if [[ ! $(echo "${tsc_offset}" | wc -w) == "1" ]]; then
+    echo "error: guest tsc offsets are inconsistent; file a bug on this script"
+    exit 1
+  fi
+fi
+
+[[ "${verbose}" == true ]] && echo "guest tsc-offset is ${tsc_offset}"
+
+"${record_cros_trace}" --ssh "${host}" -o "${host_file}" "${@:3}" &
+pids="$!"
+"${record_cros_trace}" --ssh "${guest}" -o "${guest_file}" "${@:3}" &
+pids+=" $!"
+trap "echo ; kill -s SIGUSR1 ${pids}" SIGINT
+# First wait may get canceled by the SIGINT.
+wait
+# Second wait waits for background processes to finish.
+# Don't allow SIGINT while waiting to avoid accidental interrupt.
+trap "" SIGINT
+wait
+trap - SIGINT
 
 now=$(date +"%Y-%m-%d_%H-%M-%S")
 outfile="${host}-${guest}-perfetto-trace-${now}"
 "${vperfetto_merge}" "${guest_file}" "${host_file}" "${outfile}" \
   --merge-guest-into-host --guest-tsc-offset "${tsc_offset}" && \
-  echo "./${outfile}"
+  ls -hs "./${outfile}"
+
+if [[ "${is_arcvm}" == true ]]; then
+  ssh -q "${host}" "adb shell am force-stop ${sync_app}"
+fi
 
 # merge debugging:
 #d=$(pwd)
@@ -82,6 +153,3 @@ outfile="${host}-${guest}-perfetto-trace-${now}"
 #out/linux/trace_to_text text "${host_file}" "${d}/trace-host.txt"
 #out/linux/trace_to_text text "${d}/${outfile}" "${d}/${outfile}.txt"
 #cd -
-
-# example result:
-# https://ui.perfetto.dev/#!/?s=56b8ecf223b79d8121cb228d5ad52468f7a544931433cabd1c77b46acddb81f
